// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egtzbkrztqjzutrgrlaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVndHpia3J6dHFqenV0cmdybGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDY5NTksImV4cCI6MjA2NTIyMjk1OX0.ndedSvSotY3ZKt1o21UookQ0_TKSd--RR83q3wXbxO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Import the superbase bucket which is design guidelines

const DocumentViewer = () => {
  const documentUrl = 'https://egtzbkrztqjzutrgrlaj.supabase.co/storage/v1/object/public/ds//Design%20system%20updated.docx';
  
  return (
    <div className="bg-white rounded-lg p-6 shadow-lg">
      <h3 className="text-xl font-semibold mb-4">Design System Documentation</h3>
      <a 
        href={documentUrl} 
        target="_blank" 
        rel="noopener noreferrer"
        className="bg-[#1B4B9B] text-white px-4 py-2 rounded hover:bg-[#496DAF]"
      >
        View Full Design Document
      </a>
    </div>
  );
};
