// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egtzbkrztqjzutrgrlaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVndHpia3J6dHFqenV0cmdybGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDY5NTksImV4cCI6MjA2NTIyMjk1OX0.ndedSvSotY3ZKt1o21UookQ0_TKSd--RR83q3wXbxO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);